;---------------MACRO DE PUSH ALL-------------{
; FUNÇÃO DO MACRO: PRESERVAR CONTEXTO
;
; ONDE USAR: DENTRO DE PROCEDIMENTOS OU MACROS 
; QUE UTILIZAM VARIOS REGISTRADORES
;
; COMO USAR: SOMENTE CHAMAR O MACRO E EM CON-
; TEXTOS NECESSÁRIOS
;
;  NOME: PUSH_ALL
;---------------MACRO DE PUSH ALL-------------}
PUSH_ALL MACRO
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH SI
    PUSH DI
    PUSH BP
ENDM
;--------------MACRO DE POP ALL------------{
; FUNÇÃO DO MACRO: RESTAURAR CONTEXTO
;
; ONDE USAR: DENTRO DE PROCEDIMENTOS OU MACROS
;
; COMO USAR: SOMENTE CHAMAR O MACRO E EM CON-
; TEXTOS NECESSÁRIOS
;
; NOME: POP_ALL
;--------------MACRO DE POP ALL------------}
POP_ALL MACRO
    POP BP
    POP DI
    POP SI
    POP DX
    POP CX
    POP BX
    POP AX
ENDM
;-------------MACRO DE FIM DE LINHA---------{
;
; FUNÇÃO DO MACRO: PULAR PARA A PRÓXIMA LINHA
;
; ONDE USAR: QUANDO QUISER PULAR  PARA A PRÓ-
; XIMA LINHA
;
; COMO USAR: SOMENTE CHAMAR O MACRO
;
; NOME: ENDL; VEM DE--> (END LINE)
; 
;-------------MACRO DE FIM DE LINHA---------}
ENDL MACRO
    PUSH AX
    PUSH DX
    
    MOV AH, 2
    MOV DL, 10  ; Line Feed
    INT 21h  

    POP AX
    POP DX   
ENDM
;-------------MACRO PARA LIMPAR TELA---------{
;
; FUNÇÃO DO MACRO: LIMPAR TELA
;
; ONDE USAR: QUANDO QUISER LIMPAR TODA A TELA, 
; SEJA DENTRO DE PROCEDIMENTOS OU MACROS
;
; COMO USAR: SOMENTE CHAMAR O MACRO
; 
; NOME: CLEAR_SCREEN
;
;-------------MACRO PARA LIMPAR TELA---------}
CLEAR_SCREEN MACRO
    PUSH_ALL    
    MOV AX, 600H
    MOV BH, 7H
    MOV CX, 0H
    MOV DX, 184FH
    INT 10H
    POP_ALL
ENDM
;-----------MACRO PARA EXIBIR STRING----------{
;
; FUNÇÃO DO MACRO: EXIBIR STRING
;
; ONDE USAR: QUANDO QUISER EXIBIR UMA STRING, E
; AO INVES DE USAR AH, 9; INT 21H, USAR ESTE MACRO
;
; COMO USAR: CHAMAR O MACRO, E PASSAR A STRING APÓS
;
; EXEMPLO DE USO: PRINTS STRING, ONDE STRING POSSUI
; UMA STRING
;
; NOME: PRINTS --> (PRINT STRING)
;
;-----------MACRO PARA EXIBIR STRING----------}
PRINTS MACRO STRING
    PUSH DX
    PUSH AX

    LEA DX, STRING      
    MOV AH, 9      
    INT 21h 

    POP AX
    POP DX         
ENDM

;-----------MACRO PARA PRINT CHAR------------{
;
;  FUNÇÃO DO MACRO: EXIBIR CHARACTER
;
;  ONDE USAR: QUANDO QUISER EXIBIR UM CARACTERER
;
;  COMO USAR: CHAMAR O MACRO, E PASSAR O CARACTER
;
;  EXEMPLO DE USO: PRINTC CHAR, ONDE CHAR POSSUI 
;  UM CARACTE
;
;  NOME: PRINTC --> (PRINT CHAR)
;
;-----------MACRO PARA PRINT CHAR------------}
PRINTC MACRO CHAR
    PUSH DX
    PUSH AX
    MOV AH, 2
    MOV DX, CHAR
    INT 21h
    POP AX
    POP DX
ENDM

;-----------MACRO PARA POSICIONAR CURSOR------------{
;
;  FUNÇÃO DO MACRO: POSICIONA O CURSOR NA TELA
;
;  ONDE USAR: QUANDO PRECISAR POSICIONAR O CURSOR 
;  EM UMA LINHA E COLUNA ESPECIFICOS DA TELA
;
;  COMO USAR: CHAMAR MACRO E INDICAR PARAMETROS DE
;  LINHA E COLUNA RESPECTIVAMENTE
;
;  EXEMPLO DE USO:  POS_CURSOR 10, 20
;
;  NOME: POS_CURSOR --> (POSICIONAR CURSOR)
;
;-----------MACRO PARA POSICIONAR CURSOR------------}
POS_CURSOR MACRO linha, coluna 
    PUSH AX
    PUSH DX
    PUSH BX

    MOV AH, 2 
    MOV BH, 0 
    MOV DH, linha
    MOV DL, coluna
    INT 10H

    POP BX
    POP DX
    POP AX
ENDM
;-------------MACRO DE INPUT SEM ECHO----------{
;
;  FUNÇÃO DO MACRO: FAZ UM INPUT SEM ECHO
;
;  ONDE USAR: QUANDO QUISER QUE O USUÁRIO DIGITE
;  ALGO SEM QUE O CARACTER DIGITADO SEJA ARMAZENADO
;
;  COMO USAR: SOMENTE CHAMAR O MACRO 
;
;  NOME: PPC --> (PRESSIONE PARA CONTINUAR)
;
;-------------MACRO DE INPUT SEM ECHO----------}
PPC MACRO 
    PUSH AX
    MOV AH, 7
    INT 21H
    POP AX
ENDM

;--------------MACRO PARA VERIFICAR SE EMBARCAÇÃO AFUNDOU--------------{
;
;   FUNÇÃO DO MACRO: VERIFICAR SE CARACTER DA EMBARCAÇÃO AINDA ESTA PRE
;   SENTE NO TABULEIRO
;
;   ONDE USAR: VERIFICAR SE EMBARCAÇÃO AFUNDOU
;
;   COMO USAR: CHAMAR MACRO, PASSAR O TAMANHO DA MATRIZ, A LETRA QUE QUER
;   VERIFICAR E A MATRIZ QUE QUER VERIFICAR
;
;   NOME --> AFUNDOU
;
;--------------MACRO PARA VERIFICAR SE EMBARCAÇÃO AFUNDOU--------------}
AFUNDOU MACRO COUNTER, COMPARADO, STRING

    MOV CX, COUNTER
    MOV AX, COMPARADO
    MOV DI, OFFSET STRING
    REPNE SCASW

ENDM
;------------MACRO PARA MUDAR COR DE STRING-------------{
;   
;   FUNÇÃO DO MACRO: MUDAR COR DE STRINGS TERMINADAS EM $
;
;   COMO USAR: CHAMAR MACRO, PASSAR A STRING QUE QUER MUDAR A 
;   COR E A COR PARA QUAL QUER MUDAR, EM BL É ARMAZENADA A COR
;   E EM [SI] A STRING
;
;   NOME --> PRINT_COR
;
;------------MACRO PARA MUDAR COR DE STRING-------------}

PRINT_COR MACRO STRING, COR
PUSH SI
PUSH BX 

    LEA SI, STRING
    MOV BL, COR
    CALL MUDA_COR

POP BX
POP SI
ENDM

;----------------MACRO PARA TABULAÇÃ0------------------{
;
;   FUNÇÃO DO MACRO: TABULAÇÃO, CRIAR ESPAÇOS EM BRANCO
;
;   COMO USAR: CHAMAR MACRO MAIS NUMERO DE VEZES QUE QUER QUE
;   A TABULAÇÃO SEJA APLICADA
;   
;   NOME --> TAB
;
;----------------MACRO PARA TABULAÇÃ0------------------}

TAB MACRO N                 
    PUSH AX
    PUSH BX
    PUSH CX 
    PUSH DX
        
    MOV AH, 3
    MOV BH, 0
    INT 10h
        
    MOV AH, 2
    ADD DL, N 
    INT 10h   
        
    POP DX
    POP CX
    POP BX
    POP AX
ENDM
;----------------MACRO PARA IMPRIMIR NÚMERO------------------{
;
;   FUNÇÃO DO MACRO: IMPRIMIR UM NÚMERO INTEIRO DE UMA CASA
;
;   COMO USAR: CHAMAR O MACRO COM O NÚMERO QUE DESEJA IMPRIMIR
;   
;   NOME --> PRINTNUM
;
;----------------MACRO PARA IMPRIMIR NÚMERO------------------}

PRINTNUM MACRO NUM
PUSH_ALL

MOV BL, NUM
ADD BL, 30H
MOV AH, 2
MOV DL, BL
INT 21H

POP_ALL
ENDM
